FROM node:alpine
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY ./ ./
RUN npm i
RUN npm install @mui/material @mui/styled-engine-sc styled-components
RUN npm install @mui/icons-material
RUN npm install axios
RUN npm install react-router-dom
RUN npm install react-router
RUN npm install @tanstack/react-query
RUN npm install -D tailwindcss
RUN npm install @mui/joy @emotion/react @emotion/styled
RUN npm i @tanstack/react-query-devtools
RUN npm install cypress --save-dev
COPY tailwind.config.js ./
CMD ["npm", "run", "start"]
